### ISSUE TITLE
Failure of pylint within codeclimate

### ISSUE THREAD

**Issue by spxiwh** [meuspedidos/codeclimate-pylint#24] opened 2018-10-11 09:16 UTC
Hi all, thanks for the good work in making pylint available within codeclimate! This has been really useful for us.

However, in the last week we are seeing pylint failing consistently in our codeclimate builds with:

https://codeclimate.com/github/gwastro/pycbc/builds/670

```
Traceback (most recent call last):
   File "/usr/src/app/codeclimate-pylint", line 46, in <module>
     Run(files, reporter=CodeClimateReporter(), do_exit=False)
   File "/usr/local/lib/python3.6/site-packages/pylint/lint.py", line 1394, in __init__
     linter.check(args)
   File "/usr/local/lib/python3.6/site-packages/pylint/lint.py", line 801, in check
     self._do_check(files_or_modules)
   File "/usr/local/lib/python3.6/site-packages/pylint/lint.py", line 938, in _do_check
     self.check_astroid_module(ast_node, walker, rawcheckers, tokencheckers)
   File "/usr/local/lib/python3.6/site-packages/pylint/lint.py", line 1018, in check_astroid_module
     walker.walk(ast_node)
   File "/usr/local/lib/python3.6/site-packages/pylint/utils.py", line 1162, in walk
     self.walk(child)
   File "/usr/local/lib/python3.6/site-packages/pylint/utils.py", line 1162, in walk
     self.walk(child)
   File "/usr/local/lib/python3.6/site-packages/pylint/utils.py", line 1162, in walk
     self.walk(child)
   File "/usr/local/lib/python3.6/site-packages/pylint/utils.py", line 1159, in walk
     cb(astroid)
   File "/usr/local/lib/python3.6/site-packages/pylint/checkers/typecheck.py", line 910, in visit_call
     or (isinstance(called.scope(), astroid.ClassDef)
   File "/usr/local/lib/python3.6/site-packages/astroid/node_classes.py", line 470, in scope
     return self.parent.scope()
 AttributeError: 'NoneType' object has no attribute 'scope'
```

Any suggestions on how we might go about tracking this down? I notice that you recently transitioned from the plugin using python 2 to the plugin using python 3. Our code is still using python 2 at the moment (although we are working to transition to python 3). Thanks in advance for any help that can be provided!

**Comment by caiofbpa** [comment] 2018-10-11 17:07
@spxiwh if you run `pylint` locally, can you reproduce the same error?

**Comment by caiofbpa** [comment] 2018-10-25 17:20
@spxiwh Pylint has trouble analysing Python 2 code when running in Python 3. Since it's troublesome for us to determine what Python version to run for each codebase, we'll stick with Python 3 for the time being. If this is a problem for you, I suggest you migrate to using Flake8 or another engine for general Python linting, and use Pylint solely to help you migrate to Python 3 by using its `--py3k` flag. It has been working great for us that way. I'll be closing this issue for now, let me know if you have another suggestion.

**Closed by caiofbpa** 2018-10-25 17:20 UTC
